### ISSUE TITLE
System files cannot be synchronized in Echosync 7.5

### ISSUE THREAD

**Issue by qwin163** [luminescence-software/Echosync-Support#1]
Unable to read and copy hidden files in the original folder
（无法读取和复制原始文件夹中的隐藏文件）

**Comment by CyberSinh** [comment]
Can you give me more information about the context in which this problem occurs?

**Comment by qwin163** [comment]
Hidden files in the source folder cannot be synchronized to the destination folder

**Comment by CyberSinh** [comment]
IO problems may be caused by your system, through no fault of Echosync. Given the limited information you've provided, it's impossible for me to help you identify the source of the problem.

**Comment by CyberSinh** [comment]
I have just tested the hidden file synchronization and everything worked on my side.

**Comment by qwin163** [comment]
2024-06-30 



qwin 



发件人： Sylvain Rougeaux 
发送时间： 2024-06-29  04:30:32 
收件人： luminescence-software/Echosync-Support 
抄送： qwin163; Author 
主题： Re: [luminescence-software/Echosync-Support] Echosync 7.5 bug? (Issue#1) 
 
I have just tested the hidden file synchronization and everything worked on my side.

**Comment by qwin163** [comment]
The two hidden files in the attachment cannot be synchronized, please test

**Comment by CyberSinh** [comment]
Please do not reply by email on github. For example, it is not possible to send an attachment by e-mail on github. Use your browser to visit this thread.

**Comment by qwin163** [comment]
[Hidden files.zip](https://github.com/user-attachments/files/16065467/Hidden.files.zip)

**Comment by CyberSinh** [comment]
These files are not synchronized because they have the _hidden_ attribute, but because they have the _system_ attribute.
By default, Echosync ignores files with the _system_ attribute. It is possible to include these files by setting the `IgnoreSystemFiles` parameter to `false` in the _[AdvancedSettings.json](https://www.luminescence-software.org/en/echosync/documentation#what-advanced-settings-ar)_ configuration file, located in the _Profiles_ directory.

**Comment by qwin163** [comment]
![20240702180751](https://github.com/luminescence-software/Echosync-Support/assets/174106799/4d9e10ce-6dc8-4f69-bef1-be015388da4b)
The problem is not resolved.

**Comment by CyberSinh** [comment]
You were right. _System_ files are not synchronized despite the correct setting. This is definitely a bug.
Can you test whether the problem has been solved with [version 7.5.0.5](https://www.luminescence-software.org/download/echosync/Echosync-Installer.msi)?
Thanks.

**Comment by qwin163** [comment]
OK problem solving! 


2024-07-02 



qwin 



发件人： Sylvain Rougeaux 
发送时间： 2024-07-02  19:52:37 
收件人： luminescence-software/Echosync-Support 
抄送： qwin163; Author 
主题： Re: [luminescence-software/Echosync-Support] Echosync 7.5 bug? (Issue#1) 
 
You were right. System files are not synchronized despite the correct setting. This is definitely a bug.
Can you test whether the problem has been solved with version 7.5.0.5?
Thanks.

**Comment by qwin163** [comment]
OK problem solving!
