### ISSUE TITLE
La version 7.5 n'accepte pas les chemins réseaux

### ISSUE THREAD

**Issue by guyphp1** [luminescence-software/Echosync-Support#2]
Depuis que la mise à jour à 7.5 s'est effectuée, les chemins réseaux ne sont plus accessibles.
Par exemple \\p3202\xxx n'est pas accessible. Devant le répertoire il y a le point d'exclamation dans un triangle jaune.

**Comment by CyberSinh** [comment]
Pouvez-vous me donner un exemple de chemin réseau complet (qui devrait commencer par `\\`) ?
Quelle est votre version d'Echosync (sous la forme x.x.x.x) ?

**Comment by CyberSinh** [comment]
Les chemins réseaux construits sous la forme `\\SERVER\share\folder` fonctionnent de mon côté.

**Comment by tbenelli** [comment]
Bonjour J'ai pourtant le même soucis que guyphp1 mon montage \\ds918\photo\ est en erreur . Désinstallation et réinstallation n'y change rien je suis repassé en 7.2 ma précédente version installée

**Comment by CyberSinh** [comment]
Qu'entendez-vous par "montage" ? 
Un chemin réseau absolu devrait commencer par `\\` et non `\`.
Le chemin `\\ds918\photo\` fonctionne-t-il ?

**Comment by guyphp1** [comment]
Mes chemins réseaux sont bien dans la bonne forme \\aaa\aaa et ils ne fonctionnent pas.
La version 7.2 fonctionne parfaitement avec le même profile.
Si ça fait une différence, je suis avec Windows 11

**Comment by guyphp1** [comment]
Mon commentaire précédent montre un chemin réseau précédé d'un seul \ mais il y en a 2.
C'est la gestion du commentaire qui en enlève un.

**Comment by CyberSinh** [comment]
Pouvez-vous essayer les commandes PowerShell ci-dessous et m'indiquer le résultat ?

```powershell
$uri = [System.Uri]'\\ds918\photo\'
[System.Net.Dns]::GetHostAddresses($uri.DnsSafeHost)
```

**Comment by guyphp1** [comment]
Voici le résultat:

PS C:\WINDOWS\system32> $uri = [System.Uri]'\\p3202-i3s\www_330_test\'
>> [System.Net.Dns]::GetHostAddresses($uri.DnsSafeHost)


Address            :
AddressFamily      : InterNetworkV6
ScopeId            : 9
IsIPv6Multicast    : False
IsIPv6LinkLocal    : True
IsIPv6SiteLocal    : False
IsIPv6Teredo       : False
IsIPv4MappedToIPv6 : False
IPAddressToString  : fe80::65be:198:59fa:7f38%9

Address            : 1677764800
AddressFamily      : InterNetwork
ScopeId            :
IsIPv6Multicast    : False
IsIPv6LinkLocal    : False
IsIPv6SiteLocal    : False
IsIPv6Teredo       : False
IsIPv4MappedToIPv6 : False
IPAddressToString  : 192.168.0.100

**Comment by tbenelli** [comment]
en fait github bouffe le premier slash
j'ai moi :
PS C:\Users\thier> $uri = [System.Uri]'\\ds918\photo\'
PS C:\Users\thier> [System.Net.Dns]::GetHostAddresses($uri.DnsSafeHost)

AddressFamily      : InterNetworkV6
ScopeId            : 0
IsIPv6Multicast    : False
IsIPv6LinkLocal    : False
IsIPv6SiteLocal    : False
IsIPv6Teredo       : False
IsIPv6UniqueLocal  : False
IsIPv4MappedToIPv6 : False
Address            :
IPAddressToString  : 2a01:e0a:2da:4740:211:32ff:feb4:58b7

AddressFamily      : InterNetwork
ScopeId            :
IsIPv6Multicast    : False
IsIPv6LinkLocal    : False
IsIPv6SiteLocal    : False
IsIPv6Teredo       : False
IsIPv6UniqueLocal  : False
IsIPv4MappedToIPv6 : False
Address            : 721463488
IPAddressToString  : 192.168.0.43

**Comment by tbenelli** [comment]
> Qu'entendez-vous par "montage" ? Un chemin réseau absolu devrait commencer par `\\` et non `\`. Le chemin `\\ds918\photo\` fonctionne-t-il ?
oui , et la version 7.2 l'accepte bien
désolé ce n'est pas un montage justement il y a bien les deux anti slash

**Comment by CyberSinh** [comment]
Je ne vois rien de problématique avec ces sorties. Nous allons devoir poursuivre les investigations...

Pouvez-vous exécuter le script PowerShell "DirectoryExists.ps1" ci-dessous ? 
Il faut supprimer l'extension ".txt" du nom de fichier ; Github n'autorise pas l'ajout de pièce jointe avec une extension .ps1.
[DirectoryExists.ps1.txt](https://github.com/user-attachments/files/16220279/DirectoryExists.ps1.txt)

Vous pourrez ensuite appeler la méthode suivante avec le nom de votre chemin réseau en paramètre:
`[Echosync.Directory2]::Exists("\\ds918\photo\")`

La sortie du terminal devrait m'apporter plus d'informations sur ce qui pose problème.
Merci.

**Comment by tbenelli** [comment]
Bonjour le retour est :

PS C:\tmp> [Echosync.Directory2]::Exists("\\ds918\photo\")
Test du chemin "\\ds918\photo\"...
Recherche d'un adresse IP pour le domaine "ds918"...
2a01:e0a:2da:4740:211:32ff:feb4:58b7
192.168.0.43
Adresse IP introuvable !
False

c'est bien la bonne adresse Ip V4
le pb vient 'il de ip V6 ?

**Comment by tbenelli** [comment]
à l'exécution du script j'ai :
PS C:\Windows\System32> cd \tmp
PS C:\tmp> .\DirectoryExists.ps1
PS C:\tmp> [Echosync.Directory2]::Exists("\ds918\photo")
Test du chemin "\ds918\photo"...
Un Uri ne peut être créé avec le chemin !
False

**Comment by CyberSinh** [comment]
C'est moi qui avait supprimé les WARNING car ils n'ont pas d'importance. Plus que la sortie du script, c'est la sortie de la commande `[Echosync.Directory2]::Exists("\ds918\photo")` qui m'interessait.

En revanche, ce qui est bizarre, c'est que vous n'obtieniez pas le même résultat pour cette commande, avec le même chemin. L'erreur était "Adresse IP introuvable", puis "Un Uri ne peut être créé avec le chemin".

**Comment by tbenelli** [comment]
oui  j'ai vu aussi

**Comment by tbenelli** [comment]
j'ai redémarré mon ordi puis exécuté les commandes, la deuxième après avoir lancé echosync7.22

PS C:\tmp> [Echosync.Directory2]::Exists("\\ds918\photo\")
Test du chemin "\\ds918\photo\"...
Recherche d'un adresse IP pour le domaine "ds918"...
2a01:e0a:2da:4740:211:32ff:feb4:58b7
192.168.0.43
Adresse IP introuvable !
False
PS C:\tmp> [Echosync.Directory2]::Exists("\\ds918\photo\")
Test du chemin "\\ds918\photo\"...
Recherche d'un adresse IP pour le domaine "ds918"...
Adresse IP introuvable !
False

**Comment by CyberSinh** [comment]
Après réflexion, j'ai décidé de rétablir le comportement de la version 7.2 dans la version 7.5 s'agissant de la détection de la disponibilité des dossiers.

Pouvez-vous mettre à jour votre version d'Echosync vers la version 7.5.2 que je viens de publier et m'indiquer si tout fonctionne bien de votre côté ?
[https://www.luminescence-software.org/fr/echosync/download](https://www.luminescence-software.org/fr/echosync/download)

Merci.

**Comment by tbenelli** [comment]
Bonjour je teste cela se soir sur mon ordi perso et je vous fait un retour, 
merci pour votre implication

**Comment by tbenelli** [comment]
super cela fonctionne très bien 
merci beaucoup
