### ISSUE TITLE
La comparaison est incorrecte lorsqu'un chemin racine est utilisé comme source avec Echosync 7.5.2

### ISSUE THREAD

**Issue by bodetdenis** [luminescence-software/Echosync-Support#3]
Bonjour
Je rencontre un souci avec la dernière version du logiciel Echosync.
En effet lorsque que je réalise une synchronisation d'un disque dur complet vers un dossier. (par exemple de E:\ vers F:\sauv_complete) le logiciel effectue bien la copie des fichiers mais ils sont copiés **à la racine de F:\** et non dans le dossier prévu. Tous les dossiers sont renommés en insérant sauv_complete en début de nom des dossiers. Il en est ainsi pour tous les fichiers se trouvant à la racine du disque dur.
Cordialement
Denis BODET
![20240820_echosync](https://github.com/user-attachments/assets/a87f12fe-c05d-4c8e-9117-158578fa9977)

**Comment by CyberSinh** [comment]
Ça ressemble effectivement à un vilain bug. Pouvez-vous vous essayer en décochant l'option "synchroniser les fichiers déplacés ou renommés" ?

**Comment by bbleeker** [comment]
I'm having the same problem, starting with version 7.5.2.

**Comment by bodetdenis** [comment]
Bonjour
Je précise que je travaille avec la version 7.5.3 portable.
Désolé cela ne fonctionne pas non plus si je supprime l'option "Renomme ou déplace dans le dossier de destination les fichiers et répertoires renommés ou déplacés dans le dossier source". Le logiciel considère que les fichiers existent dans le dossier de destination.
Cordialement
![20240820_echosync2](https://github.com/user-attachments/assets/11e20af4-0f4f-437f-b64b-e0ee56335acb)

**Comment by CyberSinh** [comment]
Bonjour,

Merci pour ce rapport de bug, qui a été corrigé dans la version 7.5.3.1 d'Echosync, publiée ce jour:
[https://www.luminescence-software.org/fr/echosync/download](https://www.luminescence-software.org/fr/echosync/download)

Pouvez-vous mettre à jour Echosync et me confirmer que tout fonctionne comme attendu ?

**Comment by bodetdenis** [comment]
Bonjour,
Je vous remercie de votre travail.
Après mise à jour vers la version 7.5.3.1, le fonctionnement est correct et correspond aux attendus.
Cordialement
