### ISSUE TITLE
New Echosync 7.6 is a complete mess.

### ISSUE THREAD

**Issue by chp-1960** [luminescence-software/Echosync-Support#5]
I use Echosync since years for my personal backup but the latests 7.x releases are completely a mess.
My main use of Echosync is to backup (differential backup) from my NAS HDDs to a local HDD and back if necessary.

Many aspects make me to revert back to old versions 7.2 :
- First, the new gui is harder to understand and on each action I lose time to understand if my parameters are correct.
- 2nd, the compare function take ages (up to 20mn) to achieve now where before it was done in seconds.
- 3rd, the transfert rate is slower than the previous 6.x release on the same network (2.5Gbps Ethernet). Even the tranfert from local HDDs (Raid 0/1 SSDs) to local USB Raid HDDs are slower.
- 4th, I even had some HDDs crashes I had to reinitialize and format to make them usable again.

Till these problems are not corrected, I'll stay on latest fine working version 7.2

**Comment by CyberSinh** [comment]
You mention that Echosync's performance has regressed. However, Echosync 7.6 should perform much better than previous versions. I haven't noticed any regression on my machine, and you're the first to point out such issues. 

Can you make a screencast illustrating the difference in performance when comparing identical folders between Echosync version 7.6 and 7.2?

Thanks.

**Comment by CyberSinh** [comment]
Without any return from @chp-1960, I'm closing this ticket. It will be reopened if more information is provided.
